package project.Hibernate;

public enum RecordStatusEnum {
    ADD_OBJECT, ADD_CLIENT, ADD_FACILITY, ADD_REQUIREMENT, ADD_CONSULTATION,
    ADD_AGREEMENT, UPDATE_OBJECT,  UPDATE_CLIENT, UPDATE_FACILITY,
    UPDATE_REQUIREMENT, UPDATE_CONSULTATION, UPDATE_AGREEMENT
}
